### PR TITLE
fix(flatten): use `LinkedHashSet` instead of `HashSet`

### PR DESCRIPTION
**Pull request by hoc081098**
to maintain the insertion order

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
still get error, but order is maintained in the reverse order I see 🤔 

```kotlin
@Test
    fun `allow overrides by type`() {
        val app = koinApplication {
            modules(
                module {
                    single<Simple.ComponentInterface1> { Simple.Component2() }
                },
                module {
                    single<Simple.ComponentInterface1> { Simple.Component1() }
                },
            )
        }

        app.assertDefinitionsCount(1)
        assertTrue(app.koin.get<Simple.ComponentInterface1>() is Simple.Component1)
    }
```

Good thing is that order seems stable

image

**Comment by arnaudgiuliani** [comment]
Could test that with this test too:

```kotlin
@Test
    fun test_flatten_list() {

        (1..100).all { i ->
            val modules = listOf(module { },module { },module { },module { },module { },module { },module { },module { },module { },module { })
            val flatten = flatten(modules)
            flatten.reversed() == modules
        }
    }
```

**Comment by hoc081098** [comment]
@arnaudgiuliani just updated
```diff
-ArrayDeque(modules)
+ArrayDeque(modules.asReversed())
```

**Comment by arnaudgiuliani** [comment]
Sounds good 🎉. Need to check the fails on test examples 🤔

**Comment by arnaudgiuliani** [comment]
Seen the problem. It's not from your side 👍 Will fix it

**Pull request merged**
