### PR TITLE
ref |> impl koinComponent.inject by koin.inject

### PR DESCRIPTION
**Pull request by madroidmaq**
Use `getKoin().inject` to keep inject implementation logic consistent with get and bind.

```kotlin
inline fun <reified T> KoinComponent.get(
    qualifier: Qualifier? = null,
    noinline parameters: ParametersDefinition? = null
): T =
    getKoin().get(qualifier, parameters)
```

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Good catch 👍

**Comment by arnaudgiuliani** [comment]
sorry, need to resolve conflicts of Koin 2.2.0

**Comment by madroidmaq** [comment]
> sorry, need to resolve conflicts of Koin 2.2.0

done.

**Comment by madroidmaq** [comment]
I want to know why this is closed and where is it unreasonable

**Pull request closed without merging**
