### PR TITLE
Update workmanager docs

### PR DESCRIPTION
**Pull request by fmatosqg**
For some reason I had these docs changes for a long time in my disk, still not pushed. 

Not sure if these should go in the 2.2.2 branch or master. Since I'm not up-to-date with what's going to happen to the 2.x.x versions going forward.

Cheers

### CODE REVIEW

**Comment by fmatosqg** [comment]
@arnaudgiuliani reminder to merge these docs
I'm not sure if the branch should go in master or 2.2.2, let me know how's the best way to get them going.

**Comment by arnaudgiuliani** [comment]
is it still relevant for Koin 3.1.x? WorkManager API has been updated.

**Comment by arnaudgiuliani** [comment]
Closing master branch closed all PRs :/ really sorry. Can you update your PR against main branch

**Comment by fmatosqg** [comment]
No worries, I'll try to put some time on this.

**Pull request closed without merging**
