### PR TITLE
fix creating instance with optional dependency & with parameters

### PR DESCRIPTION
**Pull request by hrach**
Sadly I am unable to make the AS / IntelliJ work with this project (is Kotlin Multiplatform needed? It does not work on Windows :()

This fixes `java.util.NoSuchElementException: ArrayDeque is empty.`  exception. More in test.

### CODE REVIEW

**Comment by hrach** [comment]
Ok, no tests here, but locally I've run `./core/tests.sh` and test are green! ✔️

**Comment by hrach** [comment]
@arnaudgiuliani hi, could you please take a look? :) thanks

**Comment by arnaudgiuliani** [comment]
Thanks @hrach. Another patch has been submitted. Let's follow on it.

**Comment by hrach** [comment]
@arnaudgiuliani Where it is was submitted? I didn't find anything in PRs/merged commits.

**Comment by arnaudgiuliani** [comment]
check on `main` branch: https://github.com/InsertKoinIO/koin/blob/main/core/koin-core/src/commonMain/kotlin/org/koin/core/scope/Scope.kt#L244

**Comment by arnaudgiuliani** [comment]
I fixed it some days ago, regarding another issue.

**Pull request closed without merging**
