### PR TITLE
Replace compile with api or implementation configuration

### PR DESCRIPTION
**Pull request by tynn**
This PR replaces all usages of `compile` dependencies and updates patch and pre-release dependency versions.

- In all libraries `compile` was replaced with `api`
- In examples `compile` was replaced with `implementation`
- In documentatin `compile` was replaced with `implementation`
- `testCompile` was always replaced with `testImplementation`
- `compileOnly gradleApi()` was used for the gradle plugin

### CODE REVIEW

**Comment by misa** [comment]
There are 3 more `compile` in `koin-androidx-scope/build.gradle`

**Comment by arnaudgiuliani** [comment]
Good catch @tynn , this was a linked issue due to bintray publish scripting. Do you other PR https://github.com/InsertKoinIO/koin/pull/925 is finally fixing it?

many thinks 🙏

**Comment by arnaudgiuliani** [comment]
For Koin 3.0, I project to restructure folders a bit to help work on focused topics (core, mp, android, ...). What do you think of having more Kotlin gradle script instead of groovy files? 🤔

**Comment by tynn** [comment]
I'm not a fan of _Kotlin_ for _Gradle_. The DSL is less flexible. Restructuring sounds good. It'll provide a better overview.

**Comment by arnaudgiuliani** [comment]
@tynn would like to wait for merge into 3.0.0 to clean it? I can let you work on that, once I've done the merge from 2.2.x to 3.0

**Comment by arnaudgiuliani** [comment]
@tynn I propose that we test your work, and then I can merge to 3.0.0. Else it's a bit too bad to loose your work :/ sorry

Let me see if jcenter publish is still working

**Comment by arnaudgiuliani** [comment]
@tynn Your changes have been ported to the new master branch and checked.

**Comment by arnaudgiuliani** [comment]
Let me know if you see other improvements to do.

**Pull request closed without merging**
