### PR TITLE
Update versions-android.gradle

### PR DESCRIPTION
**Pull request by Shusshu**
Update compose

### CODE REVIEW

**Comment by Shusshu** [comment]
https://github.com/InsertKoinIO/koin/issues/1098

**Comment by abhishekdewan101** [comment]
It would really nice to get this merged since without this we cant use compose beta-07 with koin

**Comment by Shusshu** [comment]
Yes, that was a note in #1098 ... Does koin really need kotlin 1.5.0 that's the real question.

**Comment by SergejIsbrecht** [comment]
Damn, looks like I did not see your PR. I opened up #1102 for exactly the same reason, but I just used `Kotlin` 1.4.32. I did a composite build with my project and it seems to work fine.

**Comment by Shusshu** [comment]
Your PR is perfect
Closing this one as it is super-seeded by https://github.com/InsertKoinIO/koin/pull/1102

**Pull request closed without merging**
