### PR TITLE
Breaking looping linked scopes when first got instance.

### LINKED ISSUE #689: Factory called twice
**Describe the bug**
While getting instance via factory in a root scope, the factory called only once per each get. But when factory defined in a root scope and got in a custom scope, that factory called twice per each get, for a custom scope and for a root scope.

**To Reproduce**
```
val fooModule = module {
    factory { "Some string" }  // called twice for each scope ("foo" and root scope)
    scope(named="foo") {
        scoped {
            val someString: String = get()  // called only once
            Foo(someString)
        }
    }
}
```
**Expected behavior**
I expect factory called only once.

**Koin project used and used version (please complete the following information):**
`koin-core version 2.1.0-alpha-8`
`koin-androidx-scope version 2.1.0-alpha-8`

### PR DESCRIPTION
**Pull request by scraplesh**
Fixes #689

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
thanks, will merge it soonly 👍

**Comment by arnaudgiuliani** [comment]
Hello @scraplesh ,

can you provide a test (unit test if possible) to reproduce it?

thanks

**Comment by scraplesh** [comment]
> 
> 
> Add a test case please. Check existing koin-core tests

Added test case as you requested, pushed to my fork. But this pull request not updated yet. Don't know how to properly update it with my new commit.

**Comment by arnaudgiuliani** [comment]
Try to push to `scraplesh:master`? 🤔

**Comment by scraplesh** [comment]
> 
> 
> Try to push to `scraplesh:master`? 🤔

Seems that it's a bug in github. In my repo it shows two commits and here is only one. Maybe recreate this pull request?

**Comment by scraplesh** [comment]
> 
> 
> Try to push to `scraplesh:master`? 🤔

All good, commit appeared in pull request 👍

**Pull request merged**
