### PR TITLE
Allow overriding definitions in scopes by loading modules

### PR DESCRIPTION
**Pull request by aschattney**
Previously, the definitions were not added when they were already present. Specifying the override parameter didn't work because only primaryType and qualifier are evaluated in the `hashCode()` and `equals()` method in the `BeanDefinition` class.

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Can you help and check if you have this problem in current master version? (2.1.0-alpha-6)

**Comment by arnaudgiuliani** [comment]
Can you check if this issue is still there on `2.1.0-alpha-7`?

**Comment by aschattney** [comment]
The issue is resolved :thumbsup:

**Comment by arnaudgiuliani** [comment]
good :)

**Pull request closed without merging**
