### PR TITLE
#566 Avoid recreating instance holder when it has already been created.

### PR DESCRIPTION
**Pull request by aschattney**
Fixes gh-566

### CODE REVIEW

**Comment by erickok** [comment]
lgtm

**Comment by arnaudgiuliani** [comment]
Hey @aschattney 

I'm currently rethinking the internal Koin structure to allow us to go more to immutable graph. Thus with 2 ideas:
- better synchronization 
- allow easily to go to Koin MPP

The actual structure is not so great, as I mixed the instance factory holder components too much. I would like to take the time to rewrite this in the next days.

**Comment by aschattney** [comment]
Hey @arnaudgiuliani 

I'm interested in the current status. Is there a branch with the wip changes?

**Comment by arnaudgiuliani** [comment]
Please check master, and current `2.1.0-alpha-6`. New resolution engine design should fix that

**Pull request closed without merging**
