### PR TITLE
Add Ktor 2.0 Plugin for Koin

### PR DESCRIPTION
**Pull request by phucynwa**
Since version 2.0, Ktor uses Plugin instead of Feature.

Refs #1257

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Seems still in beta, no? 🤔

**Comment by phucynwa** [comment]
@arnaudgiuliani Ktor 2.0 is still in beta. However, many Ktor project using Koin as a DI framework had migrated to 2.0 and cannot use Koin anymore. We should support them. Maybe in the beta version of Koin 3.1.6 ?

**Comment by AlexandreBrown** [comment]
@arnaudgiuliani FYI 
image
Source : Kotlin Slack

**Comment by arnaudgiuliani** [comment]
Yeah, great thing. First beta version of Koin 3.2 is starting those days until start of April (beta phase of 6 weeks). We can add Ktor 2.0 in it 👍

**Comment by CloudyDino** [comment]
Any chance this can be merged in now that Koin 3.2 beta-1 has been released?

**Comment by alexfacciorusso** [comment]
Given this seems to be a non-destructive change (e.g. it's just adding the plugin), is there any reason why this PR doesn't get taken into consideration? Thanks!

**Comment by arnaudgiuliani** [comment]
Need a last check on it, but seems ok 👍  Any impact on ktor sample app?

**Comment by phucynwa** [comment]
@arnaudgiuliani No, I created a new module for Ktor 2. No affect to the exist samples.

**Comment by arnaudgiuliani** [comment]
the interesting point here is to decide either to go Ktor 2.0 only, either to offer both. The new 3.2 branch is dedicated to new versions, that I would keep Ktor 1.6.x into Koin 3.1.x and go with ktor 2.0 in 3.2. I need to check with ktor team if their will maintain other branches of Ktor 1.x

**Comment by alexfacciorusso** [comment]
> the interesting point here is to decide either to go Ktor 2.0 only, either to offer both. The new 3.2 branch is dedicated to new versions, that I would keep Ktor 1.6.x into Koin 3.1.x and go with ktor 2.0 in 3.2. I need to check with ktor team if their will maintain other branches of Ktor 1.x

I believe it would be about keeping back-compatibility: many backends would continue using Ktor 1.x still for long time (e.g. they won't update immediately to Ktor 2 since upgrading to it might require big efforts from their side, especially for production servers and big projects), and removing the support for Ktor 1.x would mean leaving many projects without first-citizen support from Koin, which I believe would be a huge loss.

If my personal opinion would count something, I would advise against removing the support for the 1.x and instead add the v2 as additional plugin (what this PR is doing). Absolutely feel free to liaise with the Ktor team, maybe they would have other useful input

**Comment by arnaudgiuliani** [comment]
Ktor 1.x will be maintained for security patches. Those patches will be ported to Koin 3.1.x - https://medium.com/koin-developers/koin-3-2-beta-roadmap-for-2022-b3b4afea69d8

The problem now is: is there really a need to extract koin-ktor from the main release cycle, to have its own release cycle like compose or Koin annotations.

**Comment by alexfacciorusso** [comment]
> Ktor 1.x will be maintained for security patches. Those patches will be ported to Koin 3.1.x - https://medium.com/koin-developers/koin-3-2-beta-roadmap-for-2022-b3b4afea69d8
> 
> The problem now is: is there really a need to extract koin-ktor from the main release cycle, to have its own release cycle like compose or Koin annotations.

I believe that would definitely benefit the Ktor community. That said, how would the Gradle/Maven dependency be named? 
`io.insert-koin:koin-ktor2` and `io.insert-koin:koin-ktor3`, where `ktor` would initially point to ktor 2 and then ktor 3 whenever it will be released?

If so, then the documentation would need to put an alert or something to let people know of the change

**Comment by alexfacciorusso** [comment]
My suggestion is because if you simply stop updating the `io.insert-koin:koin-ktor` library, no one would know of the change of name, if it makes sense

**Comment by arnaudgiuliani** [comment]
by extracting koin-ktor project?

**Comment by alexfacciorusso** [comment]
> by extracting koin-ktor project?

yes. Extracting the ktor "plugin" in its own library it means the Ktor community can have a faster updates cycle if needed

**Comment by arnaudgiuliani** [comment]
Yes, I will extract koin-ktor development in its own project for Koin 3.2 timeline. It will be better.

**Comment by CloudyDino** [comment]
So if I'm on Ktor 2.0, will I get the update on the `io.insert-koin:koin-ktor` library or will there be a different library that I'll have to import? Just not sure what the result of extracting the koin-ktor library into its own project means for Ktor devs.

**Comment by arnaudgiuliani** [comment]
it will be the same `io.insert-koin:koin-ktor`, from version 3.2 ok Koin. We will catchup ktor 2.0 cycle.

ktor 1.6 -> Koin 3.1
ktor 2.0 -> Koin 3.2

**Comment by phucynwa** [comment]
Ktor 2.0.0 RC-1 has been released.

**Comment by geek5nan** [comment]
Not only Ktor 2.0.0-rc1 has been released, but Ktor 2.0.0 has also been released silently. 

[2.0.0](https://repo1.maven.org/maven2/io/ktor/ktor/2.0.0/) - 2022-04-08 07:10         
[2.0.0-beta-1](https://repo1.maven.org/maven2/io/ktor/ktor/2.0.0-beta-1/)   -  2021-12-22 11:27
[2.0.0-rc-1](https://repo1.maven.org/maven2/io/ktor/ktor/2.0.0-rc-1/) - 2022-04-04 13:42

**Comment by arnaudgiuliani** [comment]
from what I see, we don't need 2 packages of koin-ktor, but rather the same that evolves with Ktor versions.

**Comment by phucynwa** [comment]
I think I'll update this PR soon.

**Comment by arnaudgiuliani** [comment]
Let me create the new repo, and extract base project for it. Once ready we can move the PR

**Comment by Marek00Malik** [comment]
What is the status of this PR? 
We have to work with hacks like this [one](https://github.com/InsertKoinIO/koin/issues/1295) to work on Ktor 2.0.0.

**Comment by jmfayard** [comment]
@phucynwa could you update your PR with this gist ? https://gist.github.com/MarkusNowotny/c245b5f493bfdde09d7b9853ef91fb55

**Comment by markiewiczart** [comment]
KoinPlugin in not compatible with Ktor 2.0.1 anymore as the interface `ApplicationPlugin` changed. The new way of creating a plugin would be something like this:

```kotlin
// Config class
class KoinPluginConfiguration {
    var appDeclaration: KoinAppDeclaration = {}
        private set

    fun koin(block: KoinAppDeclaration) {
        appDeclaration = block
    }
}

// Plugin
val KoinPlugin = createApplicationPlugin(name = "KoinPlugin", createConfiguration = ::KoinPluginConfiguration) {
    val monitor = environment?.monitor
    val koinApplication = startKoin(appDeclaration = pluginConfig.appDeclaration)
    monitor?.raise(KoinApplicationStarted, koinApplication)

    monitor?.subscribe(ApplicationStopping) {
        monitor.raise(KoinApplicationStopPreparing, koinApplication)
        stopKoin()
        monitor.raise(KoinApplicationStopped, koinApplication)
    }
}

// Usage
fun Application.configureKoin() {
    install(KoinPlugin) {
        koin {
            logger(SLF4JLogger())
            modules(
                myModule(),
                module {
                    single { MyService() }
                }
            )
        }
    }
}
```

Extension functions work fine.

**Comment by arnaudgiuliani** [comment]
thanks, very helpful! I'm working on it 💪

**Comment by arnaudgiuliani** [comment]
Project is now ready for Ktor 2 in https://github.com/InsertKoinIO/koin-ktor

**Pull request closed without merging**
