### PR TITLE
README: Replace broken https://insert-koin.io/docs/setup/v3.2 links

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by sschuberth** [comment]
Meanwhile, @arnaudgiuliani had changed one of the links in https://github.com/InsertKoinIO/koin/commit/4821ef0e1e03735335350c03f63c03f87ca4952a, but I still believe my PR is the better way to fix these links.

**Review by vikrammani-t2s — APPROVED** [review]

**Comment by arnaudgiuliani** [comment]
link is working imo. not sure about what you want here

**Comment by sschuberth** [comment]
> link is working imo.

I wasn't saying that the link would *not* be working. But IMO it's more meaningful to let "Latest Version" point to https://insert-koin.io/docs/upgrade/whats-new than to https://insert-koin.io/docs/setup/koin.

> not sure about what you want here

The commit message should say it all. Just close this if you disagree with the proposal.

**Comment by arnaudgiuliani** [comment]
Let's add the link to changelog then.

**Comment by arnaudgiuliani** [comment]
current README file is updated. Also think to use GitHub release section.

**Pull request closed without merging**
