### PR TITLE
auto code format

### PR DESCRIPTION
**Pull request by drieks**
Hi @arnaudgiuliani,

I updated gradle, suppressed a warning and ran "Reformat Code" in IDEA.

### CODE REVIEW

**Comment by drieks** [comment]
also, all (except one) ktlint messages are fixed now

**Comment by arnaudgiuliani** [comment]
Thanks 👍

**Comment by drieks** [comment]
Hi @arnaudgiuliani, I think we can merge this also into master, this PR contains no functional changes.

**Comment by arnaudgiuliani** [comment]
Ok, will cherry-pick this 👍 

I see that Android projects have their source folder in `kotlin` not `java` anymore. But then, it's not scanned properly by the IDE. I can push back those folder name, what do you think?

**Pull request merged**
