### PR TITLE
Kotlin Multiplatform 1.4.0

### PR DESCRIPTION
**Pull request by uOOOO**
This PR is for #874  
There are two issues.

1. The tests can't be run due to 'Name contains illegal chars that can't appear in JavaScript identifier' error in IntelliJ. This error also occurs in Kotlin 1.3.71. I think contributors already know about this.
2. Removed watchosX86 and tvosX64 targets from koin-test module. Please refer to below log.

```
> Task :koin-test:compileTestKotlinTvosX64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':koin-test:compileTestKotlinTvosX64'.
> Could not resolve all files for configuration ':koin-test:tvosX64TestCompileKlibraries'.
   > Could not resolve com.benasher44:uuid:0.2.1.
     Required by:
         project :koin-test
      > No matching variant of com.benasher44:uuid:0.2.1 was found. The consumer was configured to find a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64' but:
          - Variant 'iosArm32-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm32' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64'
          - Variant 'iosArm64-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64'
          - Variant 'iosX64-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64'
          - Variant 'jsIr-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'tvos_x64')
          - Variant 'jsIr-runtime' capability com.benasher44:uuid:0.2.1:
              - Incompatible because this component declares a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'tvos_x64')
          - Variant 'jsLegacy-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'tvos_x64')
          - Variant 'jsLegacy-runtime' capability com.benasher44:uuid:0.2.1:
              - Incompatible because this component declares a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'tvos_x64')
          - Variant 'jvm-api' capability com.benasher44:uuid:0.2.1 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'tvos_x64')
          - Variant 'jvm-runtime' capability com.benasher44:uuid:0.2.1 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'tvos_x64')
          - Variant 'linuxArm32Hfp-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'linux_arm32_hfp' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64'
          - Variant 'linuxX64-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'linux_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64'
          - Variant 'macosX64-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'macos_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64'
          - Variant 'metadata-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'tvos_x64')
          - Variant 'mingwX64-api' capability com.benasher44:uuid:0.2.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'tvos_x64'
```

### CODE REVIEW

**Comment by GZaccaroni** [comment]
I have fixed errors due to `watchosX86` and `tvosX64` targets, by adding support to those targets to uuid library.
Please see my PR #885

**Comment by uOOOO** [comment]
> I have fixed errors due to `watchosX86` and `tvosX64` targets by adding support to those targets to uuid library (see [benasher44/uuid#99](https://github.com/benasher44/uuid/pull/99)).
> Please see my PR #885

Thank you!

**Comment by uOOOO** [comment]
I've changed com.benasher44:uuid version to 0.2.2

**Comment by arnaudgiuliani** [comment]
Ok, let's merge both work 👍

**Review by arnaudgiuliani — APPROVED** [review]

**Pull request merged**
