### PR TITLE
provide a combination of name (string) and type qualifiers together.

### PR DESCRIPTION
**Pull request by HKhademian**
now you can use qualifiers like:

    factory(named<A>("hi")){ ...}
    factory(named<B>("hi")){ ...}
    factory(named<C>("hi")){ ...}

all together.

### CODE REVIEW

**Comment by erickok** [comment]
Can you give a real-world example? Also, please read #568.

**Comment by HKhademian** [comment]
I implement clean arch. and repository pattern in android apps.

I have `...DataSource`s and for each I have api and db data-sources.

I setup koin to provide singles like:

```kotlin
val moduleA = module {
    single(named("api")) { ... } bind PostDataSource::class
    single(named("db")) { ... } bind PostDataSource::class

    single(named("api")) { ... } bind TagDataSource::class
    single(named("db")) { ... } bind TagDataSource::class
}
```

As you can see, with default qualifiers we cannot define modules like this.

**Comment by HKhademian** [comment]
After I use the patch in my app, it's hard to use `named<A>("hi")` and `named("hi")` and `named<A>()` together in a same kotlin file.

So I suggest either convert `TypeQualifier` to accept names (with null default, maintain code backward compatibility), or change this new Qualifier helper's function name to something like `typeNamed<A>("hi")`

I think if we follow the first approach will be better, because we don't have extra useless code and data structs, ...

**Comment by erickok** [comment]
Indeed this sounds more like a workaround to the issue that qualifiers cannot be used multiple times (for different types).

**Comment by HKhademian** [comment]
yes, I think `StringTypeQualifier` or `TypeQualifier` with string value is a simple solution for #462.

**Comment by arnaudgiuliani** [comment]
Your problem is solved with new resolution engine, as you can have the same qualifier with 2 different type.

Please check with `2.1.0-alpha-6`

**Pull request closed without merging**
