### PR TITLE
Allow enums to be used as Qualifiers (along with String or a class)

### PR DESCRIPTION
**Pull request by Jerbell**
This is a simple qualifier I am using and should be useful to others.  It allows an enum to be used as a qualifier.  This avoid defining equal strings in multiple areas and allows refactoring without any hidden surprises.

### CODE REVIEW

**Comment by erickok** [comment]
The idea to have a `Qualifier` interface in the first place was indeed to have (refactor) safety instead of relying on string. Why not use objects instead of an enum? Potentially together with a sealed class if you prefer.

**Comment by Jerbell** [comment]
I'd prefer to use enums rather than Objects.  An ObjectQualifier would work as well.

**Comment by erickok** [comment]
May I ask why you prefer `get(named(Way.Left))` over `get(Way.left)`?

```kotlin
sealed class Way: Qualifier {
  object Left: Way()
  object Right: Way()
}
```

**Comment by Jerbell** [comment]
You do realise the documentation only mentions String qualifiers?
https://insert-koin.io/docs/2.0/quick-references/modules-definitions/#qualifiers
You are asking why I prefer using `get(named(Way.Left))` over `get(Way.Left)` - that's not my point - I prefer defining an `enum class Way { Left, Right }` for it's simplicity, rather than a sealed class which extends Qualifier.
If there are people out there who like & use enums like myself then they will find this useful.

**Comment by erickok** [comment]
I did not realize that and consider that a weakness in the docs then. If I find time I might be able to contribute to better docs (imho better).

I suggest you should rename the `named` function as it is not a named qualifier at all, it is an enum-based qualifier. Perhaps into `qualify(MY_ENUM_VALUE)`.

**Comment by Jerbell** [comment]
Yes - `named` should be renamed.  Actually - I can use `enum` if that's clear?  I thought it would be a reserved word but apparently not in this case.
`private val rsaBits: Int = get(enum(RSA_BITS))`
What do you think?

**Comment by erickok** [comment]
I like `qualify(X)` or `qualified(X)` or `enumQualifier(X)` better, but it is up to the project maintainers.

**Comment by erickok** [comment]
Still, it effectively uses the string name, which gives unexpected non-safe behaviour. Trying to do this throws an exception with `Already existing definition`:
```
factory(enum(Way.LEFT)){ ...}
factory(named("LEFT")){ ...}
```
Worse, trying to get a qualified instance using named, e.g. `get(named("LEFT"))`, will work even if you defined only `factory(enum(Way.LEFT)){ ...}`.

**Comment by Jerbell** [comment]
So I've changed the method to `qualified` - I think it reads the best.  I've also fixed and written more tests around the potential problems.  There's a Koin/module test - hopefully I'm doing that correctly.

**Comment by arnaudgiuliani** [comment]
Hi,

I'm thinking if we could propose like `qualifier()` more than `named()`, which would accept kind of types. We can make an alias and deprecate the current API. 

then `qualifier<Enum>`, `qualifier<KClass>` or `qualifier("a string")` is more consistent for me.

**Comment by tynn** [comment]
Why don't you just define the enum class as a qualifier? It should be sufficient for most use-cases.

```
enum class Way : Qualifier {
    Left, Right
}
```

**Comment by Jerbell** [comment]
I didn't think of having an enum extend an interface.
It seems to work perfectly - thanks!  I'd recommend updating the documentation on Qualifiers.

**Pull request closed without merging**
