### PR TITLE
Add Ktor3 Package

### PR DESCRIPTION
**Pull request by chrisjenx**
Added Jar bundle for those interested until merged and deployed

Fixes: #1716 

- Fixes tests to use new `TestApplication` instead of `withTestApplication`
- Updated deprecated api's on the ktor3 module

[koin-ktor3-4.0.0-RC3.zip](https://github.com/user-attachments/files/16997826/koin-ktor3-4.0.0-RC3.zip)

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
scheduled for 4.1 👍  We will be ablet to test that before

**Comment by chrisjenx** [comment]
I copied the package into my local code base against 4.0RC2 works fine, wondering if it's work creating a 4.1 alpha? or something, not noticed any issues with 4.0 tbh (minus this one)

**Comment by ronjunevaldoz** [comment]
looking forward to this update

**Comment by sausti** [comment]
We're also looking forward to this update now that [Ktor 3.0](https://blog.jetbrains.com/kotlin/2024/10/ktor-3-0/) is released!

**Comment by zivkovic** [comment]
Is there an approximate date for when this would be available?

**Comment by arnaudgiuliani** [comment]
I should be able to check it soon. I will open 4.1.0 Beta to let you test that new package 👍

**Comment by chrisjenx** [comment]
I can bump

**Comment by arnaudgiuliani** [comment]
cool 👍

**Comment by arnaudgiuliani** [comment]
will bump version

**Pull request merged**
