### PR TITLE
Possible ConcurrentModificationException fix

### PR DESCRIPTION
**Pull request by owaineevans**
Koin was crashing with concurrency issues - this seems to fix them

### CODE REVIEW

**Comment by owaineevans** [comment]
Hi, this fix seems to be working for my project and passes all tests.

**Comment by Sloy** [comment]
Hi! Any news on this? 
This bug is stopping us from successfully migrating to Koin :(

**Comment by arnaudgiuliani** [comment]
Actually working also on optimizing search with indexes. Keep in touch.

**Comment by arnaudgiuliani** [comment]
To complete the case, can you provide some test cases please?
(Add it in the `koin-test` project)

**Comment by arnaudgiuliani** [comment]
Do you have a usecase/sample app to reproduce your multi concurrent problem with Koin?

**Comment by Sloy** [comment]
I can try to put something together

**Comment by Sloy** [comment]
I can manage to reproduce it with a test :(
I guess Android instrumentation tests are doing some more nasty stuff for us 😞

**Comment by owaineevans** [comment]
Hi,

I'll have a go at making a test this weekend. But I'm not 100% I can
reproduce it every time. We are using a ThreadPool for our network access
and injecting a single logger class at startup. The crash seemed to only
happen 1% of the time and only in release mode.

When I saw the concurrent modification crash I knew instantly we were
accessing some array from multiple threads at the same time, hence the
patch.

I've been using the fix for a few weeks and the crash has not come back.

So my guess is that to reproduce it you would need to spawn many threads of
the same class that call by inject() at the same time.

I'll see if I've got time this weekend.

**Comment by Sloy** [comment]
There's already a test in `koin-test` for that scenario. So I'm surprised the crash is actually happening.
Maybe it happens in a slightly different scenario?

**Comment by arnaudgiuliani** [comment]
@Sloy That's the point :/

**Comment by arnaudgiuliani** [comment]
I close it. Let's check it with `1.1.x`

**Comment by ravibhojwani86** [comment]
I am at  koin  1.0.2 and see this issue. As per comment above it  is supposed to be fixed in version 1.1.x, but only version  post 1.0.2 I see is 2.0.0, any idea?

**Pull request closed without merging**
