### PR TITLE
Enhance Android Instrumentation tests doc

### PR DESCRIPTION
**Pull request by cmunaro**
I know that some people get frustrated when they try to make Instrumentation test with Koin for the lack of examples. (I was one of them 😅)
I propose a documentation update to make it easier for newcomers to create instrumentation tests with Koin. 🔧
What do you think about it?

Related to https://github.com/InsertKoinIO/koin/issues/1318 and https://github.com/InsertKoinIO/koin/issues/850

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Good proposal that will help many people 👍

**Comment by sbarbour-93** [comment]
Thanks for updating the docs on this - it's a really useful update. However, I've noticed one issue though in that if the module I try to override expects parameters to be injected in order for the instance to be built then my instrumentation tests fall over when using the new `KoinTestRule` approach with a `DefinitionParameterException`.

Is there any suggestions on this? If it needs a new issue to be opened in order to review please advise.

Thanks!

@arnaudgiuliani

**Comment by CoolMind** [comment]
See https://insert-koin.io/docs/reference/koin-android/instrumented-testing/ or commits here for an updated documentation.

**Comment by maeceloacm1998** [comment]
Muito obrigado, sua solução me ajudou para fazer testes com espresso.

**Pull request merged**
