### PR TITLE
Relax type resolution constraints

### PR DESCRIPTION
**Pull request by arnaudgiuliani**
Relax type resolution constraints.  Avoid forcing T:Any / KClass<T>

### CODE REVIEW

**Comment by AnonymousWalker** [comment]
@arnaudgiuliani 
In earlier version I could do this using KoinJavaComponent
`    val service = get(Service::class.java) `

However, since this change I have to add the explicit type because it no longer infers the generic type defined
`    val service: Service = get(Service::class.java) `

I am not sure why you change it that way

**Comment by arnaudgiuliani** [comment]
what version do you talk about?

**Comment by arnaudgiuliani** [comment]
this was effectively a problem in 2.2.x version, due to a "bad" patch

**Comment by AnonymousWalker** [comment]
The latest 3.0.1-beta-2 changed to `clazz: Class<*>`
https://github.com/InsertKoinIO/koin/blob/master/core/koin-core/src/jvmMain/kotlin/org/koin/java/KoinJavaComponent.kt
where 3.0.1 was `clazz: Class<T>`
https://github.com/InsertKoinIO/koin/blob/3.0.1/core/koin-core/src/jvmMain/kotlin/org/koin/java/KoinJavaComponent.kt

**Comment by AnonymousWalker** [comment]
I have an added extension that is available for global access, which was based on the extension methods in ktor pipeline:
[org.koin.ktor.ext.KoinApplicationCallExt](https://github.com/InsertKoinIO/koin/blob/master/ktor/koin-ktor/src/main/kotlin/org/koin/ktor/ext/KoinApplicationCallExt.kt)

Please find the proposed change here:
https://github.com/InsertKoinIO/koin/compare/master...AnonymousWalker:anonymouswalker-koin-common

**Pull request merged**
