### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by wiryadev**
Fix typos across `.md` and `.adoc` files for better documentation. No technical change here since this is solely documentation improvement.
Original PR: : #1205

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Thanks for all this. There is some conflicts, if you can solve them 🙏

**Comment by wiryadev** [comment]
I have resolved the conflicts, i think it should be okay now

**Review by arnaudgiuliani — APPROVED** [review]

**Comment by arnaudgiuliani** [comment]
Seems that your commits are not signed: `The base branch requires all commits to be signed.`

**Comment by wiryadev** [comment]
Due to problem with my GPG (windows user), i'm going to close this.

**Pull request closed without merging**
