### PR TITLE
Deprecate direct usage of Mockito in koin-test

### PR DESCRIPTION
**Pull request by tynn**
Related to #392 and #527 I rewrote `declareMock` to rely on `declare` to override the dependency.

### CODE REVIEW

**Comment by erickok** [comment]
Excellent, I strongly agree with this and with the code in this PR. 👍

**Comment by arnaudgiuliani** [comment]
New internal design is also in progress ... I will explain more about that when it's ready.

**Comment by tynn** [comment]
@arnaudgiuliani due to the deprecation with this version it should be easier to keep it and remove it with the code. It could be set to `compileOnly` though.

**Comment by arnaudgiuliani** [comment]
Just rewrite internals to fix scope, memory/immutable graph problem ... 
And then put the hands in koin-test:

Here is the new shape of mocking (without any more link to mockito):

```kotlin
class CoffeeMakerTest : KoinTest {

    private val coffeeMaker: CoffeeMaker by inject()
    private val heater: Heater by inject()

    @get:Rule
    val koinRule = KoinTestRule.create {
        printLogger(Level.DEBUG)
        modules(coffeeAppModule)
    }

    @get:Rule
    val mockProvider = MockProviderRule.create { clazz ->
        Mockito.mock(clazz.java)
    }

    @Test
    fun testHeaterIsTurnedOnAndThenOff() {
        declareMock<Heater> {
            given(isHot()).will { true }
        }

        coffeeMaker.brew()

        verify(heater, times(1)).on()
        verify(heater, times(1)).off()
    }
}
```

**Comment by arnaudgiuliani** [comment]
@tynn could you check on current master, if it's away from your proposal?

**Comment by arnaudgiuliani** [comment]
as the mockito is externalised, I kindof think we should provide default mock providers:

this has to be done by hand:

```
 @get:Rule
    val mockProvider = MockProviderRule.create { clazz ->
        Mockito.mock(clazz.java)
    }
```

**Comment by tynn** [comment]
I think the `CoffeeMakerTest` is still failing. Somehow `declare` doesn't have any effect. I'll have a look at it again. @arnaudgiuliani maybe you notice the issue directly.

**Comment by tynn** [comment]
I think I found the last issue. All tests are passing. `declare` uses `intance::class` instead of the reified `T::class`. Also I removed all deprecated inline functions. They are not used on runtime and on compiletime the new ones would be prefered anyhow.

**Comment by arnaudgiuliani** [comment]
It has to be part of the documentation to setup the Mock provider now

**Pull request merged**
