### PR TITLE
Add Koin extensions on Ktor ApplicationCall class

### PR DESCRIPTION
**Pull request by gps**
Hi @arnaudgiuliani,

First off, Koin is an awesome library, thank you for all your work on it!

As I was working on a Ktor project I realized I needed these extension functions on ApplicationCall as well. I've copied these over from the neighboring Routing and Route files.

I tried this in one of my side projects and it *seems* to work, but I'm not sure if I'm doing something stupid here as I've only just started using Koin & Ktor.

Thanks!

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Hello @gps 

thank you very much for you contribution. Could you complete current hello-ktor sample app with that or add a test somewhere?

thanks :)

**Comment by gps** [comment]
> Could you complete current hello-ktor sample app with that or add a test somewhere?

@arnaudgiuliani Done 😀.

**Comment by arnaudgiuliani** [comment]
Good job @gps 👍

**Comment by arnaudgiuliani** [comment]
Thanks for your contribution

**Pull request merged**
